### ISSUE TITLE
Customise documentation for JaponicusDB (was: pages where "PomBase" is still mentioned)

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#3] opened 2021-05-11 10:30 UTC
http://japonicusdb.kmr.nz/submit-data
 Tab 'curation statistics'  https://curation.pombase.org/pombe/stats/annotation

http://japonicusdb.kmr.nz/status/sequencing-status
requires new text (or remove page) ask Snezhana

http://japonicusdb.kmr.nz/datasets

http://japonicusdb.kmr.nz/downloads/chado-database-dumps

remove the following pages/menu item
http://japonicusdb.kmr.nz/status/sequencing-updates
http://japonicusdb.kmr.nz/status/statistics
http://japonicusdb.kmr.nz/status/gene-characterisation
http://japonicusdb.kmr.nz/status/priority-unstudied-genes
http://japonicusdb.kmr.nz/documents

keep these but:
http://japonicusdb.kmr.nz/status/gene-coordinate-changes
http://japonicusdb.kmr.nz/status/new-and-removed-genes
These pages will be blank, but many gene structures will need fixing. Ideally these will bein to be fixed, but it would be easier if  bigger contigs were available first

Still to do
Community
About
Help

**Comment by kimrutherford** [comment] 2021-05-11 10:44
Removing links it easy but we need to decide what to do with the links that go to documentation pages.  Currently there is a single "docs" directory.  If we copy the directory for japonicus it will be an ongoing maintenance job because it's got everything (including FAQ pages which aren't all relevant for japonicus).

Needs a bit of thought.

**Comment by ValWood** [comment] 2021-05-11 10:50
For the documentationn FAQ could we have some sort of flag to say if they are also relevant to japonicus? is that possible?

**Comment by kimrutherford** [comment] 2021-05-11 11:04
We probably could but there are many FAQ entries that are relevant but mention pombe, pombase, S. pombe or pombase.org in the text.  They'll need to be edited for japonicus.

**Comment by ValWood** [comment] 2021-07-20 07:19
Actually, not in the list.
 - Slim page text
 - EsyN

**Comment by ValWood** [comment] 2021-07-20 10:02
Need to list which pages are of which type.

**Comment by kimrutherford** [comment] 2021-07-22 05:54
As a first step I've created a separate JaponicusDB news feed directory: https://github.com/pombase/website/tree/master/src/docs/news.JaponicusDB  (#26)

@mah11 From now on PomBase news items should go here: https://github.com/pombase/website/tree/master/src/docs/news.PomBase

**Comment by mah11** [comment] 2021-07-22 08:33
> From now on PomBase news items should go here: https://github.com/pombase/website/tree/master/src/docs/news.PomBase

That explains the huge output list from today's `git pull`!

**Comment by kimrutherford** [comment] 2021-07-23 03:17
As a next step, I've added a way to selectively include Markdown text depending on which database the documentation is used for.

(I've added this to the [documentation for the documentation](https://github.com/pombase/website/wiki/Documentation-with-Markdown#pombase-and-japonicusdb-specific-sections))

The magic (and ugly) new directive to start a database specific section is:
```tex
%%if db=PomBase`
```

And to end a section:
```tex
%%end db=PomBase`
```

Example:

```tex
## some heading

This text will be included in both PomBase and JaponicusDB.

%%if db=PomBase
This text will only appear in the PomBase documentation.
%%end db=PomBase

Some text for both DBs.

%%if db=JaponicusDB
Some documentation for JaponicusDB
%%if db=JaponicusDB

```

To include part of a line or paragraph, split the line and insert the magic directive with no blank lines around it.  For example for this bit from `advanced-search.md`:

```
 3. Select columns to display. A set of gene expression data sets are
 hidden by default; click "Show gene expression columns" to reveal the
 additional options.
```
 the second sentence can be PomBase only like this:

```
 3. Select columns to display.
 %%if db=PomBase
 A set of gene expression data sets are
 hidden by default; click "Show gene expression columns" to reveal the
 additional options.
 %%end db=PomBase
```

For PomBase that's equivalent to:

```
 3. Select columns to display.
 A set of gene expression data sets are
 hidden by default; click "Show gene expression columns" to reveal the
 additional options.
```

Otherwise it's:
```
 3. Select columns to display.
```

**Comment by kimrutherford** [comment] 2021-07-23 06:05
Next step:
It's now possible to use variables to substitute things like database name and various ways of presenting organism names into the HTML.

I've committed an example of this in `advanced-search.md` to test that everything works:

```
The ${database_name} advanced search allows you to construct complex queries
for *${common_name}* genes. At present all advanced search results are lists
of genes that match the query specifications. Hints for specific
searches are available in the [PomBase FAQ](/faq), and linked
[below](#search-tips).
```
for Pombase this is the same as:
```
The PomBase advanced search allows you to construct complex queries
for *S. pombe* genes. At present all advanced search results are lists
of genes that match the query specifications. Hints for specific
searches are available in the [PomBase FAQ](/faq), and linked
[below](#search-tips).
```

I haven't changed any other files.

For completeness here are the possible variables and their values:

|String in Markdown|PomBase result in HTML|JaponicusDB result|
|-|-|-|
|`${database_name}`|PomBase|JaponicusDB|
|`${genus_and_species}`|Schizosaccharomyces pombe|Schizosaccharomyces japonicus|
|`${genus}`|Schizosaccharomyces|Schizosaccharomyces|
|`${species}`|pombe|japonicus|
|`${common_name}`|S. pombe|S. japonicus|

These are all obvious except for "common_name".  Let me know if you have a better name for that one.

I've added documentation here: https://github.com/pombase/website/wiki/Documentation-with-Markdown#substituting-variables

**Comment by kimrutherford** [comment] 2021-07-23 08:35
Next step:
As with the news directory it's now possible to database specific ".md" files.

For example to include the pombe sequencing-status documentation only in PomBase we can rename:
`src/docs/status/sequencing-status.md`
to:
`src/docs/status/sequencing-status.PomBase.md`

I've checked-in this change to test that everything works OK.

If it makes sense to have a similar page for japonicus, we'd make a file named:
`src/docs/status/sequencing-status.JaponicusDB.md`
(I haven't done that)

If we didn't want a japonicus status page we would need to remove the links to the sequencing-status page too.  For example in `src/docs/status/index.md` we would need to wrap the table row the includes the link in the conditional directives: 
```tex
...
| [Genome statistics](status/statistics) | Latest information on the status of the genome |
%%if db=PomBase
| [Sequencing status](status/sequencing-status) | Contig size, gap status and progress, including [centromeres](status/centromeres) and [telomeres](status/telomeres) |
%%end db=PomBase
| [Sequence updates](status/sequencing-updates) | Changes to the genome sequence since July 2003 |
| [Sequence updates pending](status/sequence-updates-pending) | Pending changes, mainly from the Broad Institute, some supported by data from other sources |
...
```
(I haven't done that either)

Note that the link to a DB specific file should not include the `.PomBase`/`.JaponicusDB` suffix as the processing script sorts that out.  So we use something like `[Sequencing status](status/sequencing-status)` even if there is a DB-specific sequencing-status file or if each DB has a sequencing-status file.


-------------

I've added this to the documentation here: https://github.com/pombase/website/wiki/Documentation-with-Markdown#database-specific-documentation-files

**Comment by mah11** [comment] 2021-07-23 08:43
This looks remarkably cool (so here I am, remarking).

> These [variables] are all obvious except for "common_name". Let me know if you have a better name for that one.

How about `species_abbrev`? Spelling out "abbreviation" would be a pain, but to a pedant like me, the "common name" for both S.p. and S.j. is (wait for it) "fission yeast".

**Comment by kimrutherford** [comment] 2021-07-23 09:11
> How about species_abbrev

Thanks, that's an improvement.  I've made that change.

**Comment by kimrutherford** [comment] 2021-07-28 04:59
Let have a chat about the next steps on Zoom today.

My suggestion is that we first identify those documentation pages that are definitely PomBase-only and add the `.PomBase` in the filename.  That won't change how the documentation looks for PomBase but we'll be able to ignore those files in the rest of the process.

This trick works for FAQ entries too.  As an test, I've renamed:
```
src/docs/faq/is-the-s-pombe-transcriptome-available-in-fasta-format.md
```
to:
```
src/docs/faq/is-the-s-pombe-transcriptome-available-in-fasta-format.PomBase.md
```
which disappears that FAQ entry on the JaponicusDB site.

This mass renaming will leave a bunch of broken links in the JaponicusDB documentation because of missing pages.  I've written a script that will have a go at finding and reporting these links.  I think it should work fine on a Mac.  To run it for PomBase use this command in the main `website` directory:
```sh
./etc/check_docs_broken_links.pl src/docs src/assets PomBase
```

Here's what the output currently looks like:  [pombase_broken_links.txt](https://github.com/japonicusdb/japonicus-config/files/6890346/pombase_broken_links.txt)
(The format is `<file_name>:<line_number>  <link>`, and then the full line where the problem was spotted)

Only 12 warnings, which I think is pretty impressive given how much documentation there is.

There are probably some false positives in that output.  Let me know if you find any and I'll tweak the script.

For the remaining files that could be useful for both PomBase or JaponicusDB I'm happy to semi-automatically change "PomBase" to "${database_name}" and replace the other strings at the same time ("\*S. pombe\*" to "\*${species_abbrev}\*").  After doing that I can check that nothing got mucked up by comparing the HTML before and after substitution to make sure it's identical.

Then we have the slow job of removing text and links from JaponicusDB using `%%if db=PomBase`/`%%end db=PomBase`.

**Comment by kimrutherford** [comment] 2021-07-28 07:58
> Let have a chat about the next steps on Zoom today.

I've been informed that it's not actually Thursday today.  It's Wednesday.  I wish someone had told me earlier.

Anyway, I'm going to edit that comment and hide this one.

We won't speak of this again.

**Comment by ValWood** [comment] 2021-07-28 09:28
That's. OK, if it suits  why don't you chat with @mah11 about this today and I will cancel Thurs morning meeting since you are already chatting with Snezka at 11?

If  it suits you better can be tomorrow.

**Comment by kimrutherford** [comment] 2021-07-28 09:40
Midori is busy writing the paper and there's no rush.  We can do a quick update at the Thursday meeting.  I'll only be chatting to Snezhka for 10 minutes.

**Comment by kimrutherford** [comment] 2021-07-30 03:58
As promised on Zoom here are the details of how to generate the HTML from the command line: https://github.com/pombase/website/wiki/Generating-documentation-HTML-after-Markdown-is-added-or-edited

Please let me know if there is anything missing, like depedencies.

**Comment by kimrutherford** [comment] 2021-07-30 04:06
Also as promised on Zoom, here is a page of all the documentation files for sorting through: https://github.com/japonicusdb/japonicus-config/wiki/All-documentation-paths

Val, this is the first step in trying to do this:

> My suggestion is that we first identify those documentation pages that are definitely PomBase-only and add the .PomBase in the filename. That won't change how the documentation looks for PomBase but we'll be able to ignore those files in the rest of the process.

**Comment by mah11** [comment] 2021-08-02 13:11
> ...  here are the details of how to generate the HTML from the command line ...

Thanks - my IT team installed stuff and I've just tested it. Looks like it worked. Hooray!

**Comment by kimrutherford** [comment] 2021-08-03 04:11
> Thanks - my IT team installed stuff and I've just tested it. Looks like it worked. Hooray!

Excellent!

Have you had a chance to try running the link checker?:

```
./etc/check_docs_broken_links.pl src/docs src/assets PomBase
```

**Comment by mah11** [comment] 2021-08-03 08:57
> Have you had a chance to try running the link checker?

.... Er, I have now :blush: Looks good - I got the same 12 duff links as you saw last week (and I put fixing them on my to-do list).

**Comment by kimrutherford** [comment] 2021-08-03 23:56
The link checker now runs on every check-in to help catch future problems.

**Comment by mah11** [comment] 2021-08-06 15:09
progress update: I've gone through and checked all of the non-FAQ pages on the list linked to [this comment](https://github.com/japonicusdb/japonicus-config/issues/3#issuecomment-889612340). When I've sorted the FAQ I'll probably upload a file here with notes on my findings. happy weekend!

**Comment by mah11** [comment] 2021-08-10 15:17
It's update time again!

I have now slogged through all the FAQs and my brain is mush ..... er, more seriously: I have a few questions...
- There are a bunch of items where the "Q" mentions pombe or PomBase, but the equivalent would be relevant for JaponicusDB. Should I/we create a copy with the S.j.-relevant question?
- Does variable interpolation include the category flags, i.e. will `pombase_categories` be automagically swapped for `japonicusdb_categories`?
- Will query links automagically work for JaponicusDB?

... and a couple of more general issues:
- I don't really know what (if anything) is happening with S.j. telomeres, rDNA, and mating type locus, which affects some of the calls about which pages are relevant, and some content of other pages.
- There are a few places where it looks like life will be easier if we add a couple more variables. Is this a good idea? If so, I've though of URLs and helpdesk email so far, a la:
    - `${base_url}`	www.pombase.org | www.japonicusdb.org
    - `${helpdesk}`	helpdesk@pombase.org | ?? (same as pombase now, new address later?)
- I put the results of my initial pass in a new tab-delimited file that I'm about to upload. Keep an eye out for question marks (`?`) because those denote things I'm not sure about.

[website-doc-paths.csv](https://github.com/japonicusdb/japonicus-config/files/6962779/website-doc-paths.csv) effin github doesn't support `.tsv` 


I think if the outstanding questions are easy to answer, then we're in good shape. I don't think the documentation revamp would be finished (or even "finished") in just a week or so, but it does seem realistic to get it close enough that we could release JaponicusDB and then carry on updating.

**Comment by kimrutherford** [comment] 2021-08-10 19:25
Thanks for slogging.

> There are a bunch of items where the "Q" mentions pombe or PomBase, but the equivalent would be relevant for JaponicusDB. Should I/we create a copy with the S.j.-relevant question?

If the only different is "pombe" or "PomBase" I think we can just use "${species}" etc. and just have one file.

> Does variable interpolation include the category flags, i.e. will pombase_categories be automagically swapped for japonicusdb_categories?

Yes, if I understand your question.  I should probably have named that flag "faq_categories" or something.  If we need PomBase or JaponicusDB specific categories we have to have a think about things.

> Will query links automagically work for JaponicusDB?

Yep, except for the ones with "results/from/id" in the URL.  `predefined_queries` should work as look as there's an entry in `japonicus-config/japonicus_site_config.json`.

> There are a few places where it looks like life will be easier if we add a couple more variables. Is this a good idea?

Good plan.  I'll add those now.

**Comment by kimrutherford** [comment] 2021-08-10 22:50
>   ${base_url}	www.pombase.org | www.japonicusdb.org
 
Done.

>  ${helpdesk}	helpdesk@pombase.org | ?? (same as pombase now, new address later?)

I went for `helpdesk_address` because it's slightly more precise and it matches what's in the config file.

**Comment by mah11** [comment] 2021-08-11 09:07
> I went for `helpdesk_address` ...

Sounds good; thanks!

> If we need PomBase or JaponicusDB specific categories we have to have a think about things.

My Plan A is to try hard to avoid needing db-specific FAQ categories. If that fails, plan B can be to handle it with clever category designations.

**Comment by mah11** [comment] 2021-08-12 13:15
Here's the second-easiest list: pages that don't need any db-specific bits (tho many will need variable interpolation deployed):

about/terms-of-use.md	confirm licenses with Snez. (et al.?)
community/fission-yeast-community-curation-pilot-project.md
community/index.md
documentation/annotation-extension-relation-display.md
documentation/gene-page-external-references.md
documentation/gene-page-gene-expression.md
documentation/gene-page-literature.md
documentation/gene-page-modifications.md	unless we should make it explicit that the example genes are S.p.
documentation/gene-page-phenotypes.md
documentation/gene-page-protein-features.md
documentation/gene-page-sequence.md
documentation/gene-page-transcript.md
documentation/genetic-and-physical-interactions.md
documentation/genotype-page.md
documentation/motif-search.md
documentation/publication-page.md
downloads/protein-datasets.md	assuming linked files & urls can be done automagically
faq/can-i-convert-a-file-from-gff-to-gtf.md
faq/can-i-convert-a-file-from-gtf-to-gff3.md
faq/can-i-do-an-enrichment-analysis-using-phenotypes.md
faq/can-i-download-sequences-for-many-genes-at-once-including-flanking-regions.md
faq/can-i-download-the-sequence-for-a-whole-chromosome.md
faq/can-i-export-data-for-a-sequence-region-from-the-genome-browser.md
faq/can-i-provide-a-list-of-genes-to-search-on.md
faq/can-i-retrieve-functional-annotations-for-genes-in-a-list.md
faq/can-i-search-for-a-gene-list-and-retrieve-results-in-the-same-order-as-in-the-input-list.md
faq/can-i-share-my-search-results.md
faq/can-i-use-a-wild-card-at-the-beginning-of-a-search-string.md
faq/can-i-use-blast-to-search-for-short-sequences.md
faq/can-i-view-my-data-privately-in-the-genome-browser.md
faq/can-i-view-my-protein-of-interest-in-a-multiple-alignment-with-related-proteins-in-other-species.md
faq/can-i-view-nucleotide-sequence-in-the-genome-browser.md
faq/do-i-need-a-password-to-download-from-the-ftp-site.md
faq/help-with-canto-access.md
faq/how-can-i-browse-the-phenotype-ontology-fypo.md
faq/how-can-i-display-a-sequence-region-using-sequence-coordinates-in-the-genome-browser.md
faq/how-can-i-find-all-s-pombe-proteins-in-a-particular-protein-family.md	separate copy to put correct species in page name/url?
faq/how-can-i-find-all-sequence-features-in-a-region-using-chromosome-coordinates.md
faq/how-can-i-find-genes-in-a-region-using-chromosome-coordinates.md
faq/how-can-i-find-genes-with-a-specific-activity.md
faq/how-can-i-find-modifications-for-my-protein-of-interest.md
faq/how-can-i-find-mutants-with-increased-or-decreased-sensitivity-to-chemicals.md
faq/how-can-i-find-proteins-that-have-transmembrane-domains.md
faq/how-can-i-find-rrna-genes.md
faq/how-can-i-find-significant-shared-fypo-annotations-for-genes-in-a-list.md
faq/how-can-i-find-snorna-genes.md
faq/how-can-i-find-transcription-factors-and-their-targets-in-pombase.md
faq/how-can-i-get-my-data-into-pombase.md?	links variable-interpolatable?
faq/how-can-i-identify-all-of-the-genes-that-affect-a-process.md
faq/how-can-i-retrieve-a-gene-sequence-including-upstream-and-downstream-sequences.md
faq/how-can-i-retrieve-sequences-for-non-protein-coding-genes.md	assuming file generated for S.j.
faq/how-can-i-retrieve-sequences-in-a-fasta-file-with-custom-headers.md
faq/how-can-i-retrieve-the-sequence-of-a-region-using-sequence-coordinates.md
faq/how-can-i-search-for-genes-involved-in-both-a-go-process-and-regulation-of-the-process.md
faq/how-can-i-see-nucleotide-level-similarity-between-s-pombe-and-other-schizosaccharomyces-species.md
faq/how-can-i-show-or-hide-tracks-in-the-genome-browser.md
faq/how-do-I-change-the-track-scale-in-jbrowse.md
faq/how-do-i-cite-data-from-pombase-how-do-i-cite-the-genome-sequence-comparison-data-etc.md
faq/index.md
faq/what-is-an-annotation-extension.md
faq/what-is-bam-format.md
faq/what-is-bed-format.md
faq/what-is-bedgraph-format.md
faq/what-is-bigbed-format.md
faq/what-is-bigwig-format.md
faq/what-is-gff3.md
faq/what-is-go-term-enrichment-how-can-i-do-it-for-my-genes.md
faq/what-is-psl-format.md
faq/what-is-vcf.md
faq/what-is-wig-format.md
faq/where-can-i-download-the-genome-sequence.md
faq/why-are-go-terms-missing-from-the-downloadable-annotation-file.md
faq/why-are-some-genes-annotated-to-both-viable-and-inviable-phenotypes.md
faq/why-are-some-genes-with-an-abnormal-phenotype-annotated-to-the-corresponding-go-process-while-others-are-not.md?	check cell cycle gene count
help/index.md	where are these? but presumably, yes, copy for S.j.
help/menu.md	''
status/chromosome-summary.md
submit-data/index.md
submit-data/menu.md

**Comment by kimrutherford** [comment] 2021-08-14 04:40
> As promised on Zoom here are the details of how to generate the HTML from the command line: https://github.com/pombase/website/wiki/Generating-documentation-HTML-after-Markdown-is-added-or-edited

I've added a new dependency for generating the docs: "jq"
The Ubuntu package for it is cleverly named: "jq"

**Comment by kimrutherford** [comment] 2021-08-14 10:21
> As promised, here's a list of pages that apply only to PomBase.

Thanks for the lists.

> For these, we may (or definitely will) want a JaponicusDB page, but we wouldn't use any of the PomBase page:

I've renamed the pages in this list and made an empty placeholder ".md" file for japonicus.  For example I've renamed:
`src/docs/about/resource-metrics.md` to `src/docs/about/resource-metrics.PomBase.md` but also created `src/docs/about/resource-metrics.JaponicusDB.md`

I've tried to do sensible renaming when "pombase" appears in the file name.  For example I've renamed:
`src/docs/about/citing-pombase.md` to `src/docs/about/citing-pombase.PomBase.md` but also created `src/docs/about/citing-japonicusdb.JaponicusDB.md`.  That makes for some redundancy in the filename which we might want to fix later.

> These don't need a JaponicusDB page at all, as far as I can tell:

Great.  I've renamed all those.

After all the renaming I checked that the same HTML is generated for PomBase and I ran `check_docs_broken_links.pl` and there are no reported problems.

**Comment by mah11** [comment] 2021-08-16 09:52
Excellent. ... just watching the huge update report scroll by .... thanks :)

What's the best thing for me to work on next? Is it time to bite the bullet and start marking off "if db=yada" lines?

**Comment by kimrutherford** [comment] 2021-08-16 10:27
> Is it time to bite the bullet and start marking off "if db=yada" lines?

That makes sense.  I'm happy to help with editing or with checking afterwards.

If you'd prefer I could first change "PomBase" to "${database_name}" etc. everywhere.  I don't think it makes a big different which we do first.

**Comment by mah11** [comment] 2021-08-16 10:40
I'm not sure I have a preference which happens first. But if you want a window to plug in the "${yada}" variables, I could work on the manuscript today (fiddly bits to do, oh joy) and move back to documentation tomorrow.

**Comment by kimrutherford** [comment] 2021-08-16 10:48
Sounds good.  I'll go through the docs and substitute the variables tomorrow (or overnight depending on your point of view).

**Comment by kimrutherford** [comment] 2021-08-17 02:22
I've just added a new variable "lc_database_name" to get the lower case version of ${database_name}: "pombase" or "japonicusdb".

I've just used it to make this Markdown line work in both DBs:
```markdown
The [Citing PomBase](/about/citing-pombase) page lists papers to cite
```
->
```markdown
The [Citing ${database_name}](/about/citing-${lc_database_name}) page lists papers to cite
```

**Comment by kimrutherford** [comment] 2021-08-17 09:43
I've added `${ncbi_taxon_id}` too.

I'm not finished doing the searching and replacing  Hopefully will be done in the next hour or two.

**Comment by kimrutherford** [comment] 2021-08-17 12:02
> I'm not finished doing the searching and replacing.

Done, I think.  The slow bit was going through changes looking for places where the substitution didn't make sense.  I'm sure I've missed many cases.  But I've checked that the generated HTML looks the same before and after so I'm confident that at least I haven't mucked up the PomBase documentation.

If you see an un-substituted string it's probably because the substitution didn't make sense or I wasn't sure if the substitution made sense.  So I left them for manual investigation.

I don't know if it will help, but while checking the changes I made a few notes of files that need an extra look.  Some are in the list because the file has "pombase" or "pombe" in the name, which isn't the end of the world but might be worth changing one day.  Some are in the list because they might be PomBase-only (like "status/centromeres.md"). 

src/docs/faq/do-i-need-a-password-to-download-from-the-ftp-site.md
src/docs/faq/how-are-pombase-systematic-ids-determined.md
src/docs/faq/how-can-i-find-s-pombe-orthologs-for-species-other-than-human-and-s-cerevisiae.md
src/docs/faq/how-can-i-find-transcription-factor-binding-sites-in-pombase.md
src/docs/faq/how-can-i-locate-centromeres.md
src/docs/faq/how-can-i-locate-telomeres-and-subtelomeric-regions.md
src/docs/faq/how-can-i-search-for-the-s-cerevisiae-ortholog-s-homolog-s-of-an-s-pombe-gene.md
src/docs/faq/where-can-i-find-information-about-pombase-data-versions.md
src/docs/faq/why-are-go-annotations-different-between-pombase-and-uniprot-goa.md
src/docs/faq/can-i-download-the-interaction-data-used-by-esyn.md
src/docs/faq/can-i-find-all-of-the-unconserved-orphan-genes-in-fission-yeast.md
src/docs/faq/can-i-find-replication-origins-in-pombase.md
src/docs/faq/can-i-retrieve-annotations-to-metabolic-databases-such-as-ec-metacyc-reactome-or-rhea-for-s-pombe-genes.md
src/docs/faq/can-i-view-variation-data-in-pombase.md
src/docs/faq/how-can-i-find-go-annotations-for-other-schizosaccharomyces-species-e-g-s-japonicus.md
src/docs/faq/how-can-i-find-s-pombe-orthologs-of-a-human-gene.md
src/docs/faq/how-can-i-see-nucleotide-level-similarity-between-s-pombe-and-other-schizosaccharomyces-species.md
src/docs/faq/how-are-sequence-feature-types-defined-in-pombase.md
src/docs/status/centromeres.md
src/docs/status/gene-characterisation-statistics-history.md
src/docs/submit-data/gene-naming-guidelines.md
src/docs/faq/can-i-download-the-interaction-data-used-by-esyn.md

**Comment by mah11** [comment] 2021-08-17 12:07
Great! I can cross-check this list with my notes. I guess I'll crack on with "if db", and try not to break anything.

**Comment by kimrutherford** [comment] 2021-08-17 12:25
> I guess I'll crack on with "if db", and try not to break anything.

Thanks.

I noticed that after the substitutions the link checking script was giving some spurious warnings.  I've fixed to cope with processing the variables but it now needs the config file as a final argument (instead of "PomBase"):

```
./etc/check_docs_broken_links.pl src/docs src/assets <WEBSITE-CONFIG-PATH>/pombase_v2_config.json
```

For me that's:

```sh
./etc/check_docs_broken_links.pl src/docs src/assets ~/pombase-config/website/pombase_v2_config.json
```

**Comment by kimrutherford** [comment] 2021-08-17 12:58
One last thing.  The script to generate the HTML from the Markdown now gives a bunch of message like:
```
[WARNING] Duplicate identifier 'pombetalks-may-th' at line 314 column 1
```

Some menu links in the news archive scroll to the wrong place because of this problem that it's complaining about.

These are generated by Pandoc but were being hidden because I misread the documentation.  From a quick look I think they all or nearly all caused by a problem with my script that calls Pandoc.  I'll make a separate issue and fix things tomorrow.

**Comment by kimrutherford** [comment] 2021-08-18 01:25
I realised that the link checker script wasn't Markdown links that started with a slash.  For example "\[bigBed](/faq/what-bigbed-format)".  Whoops.  I fixed that and then fixed as many warnings as I could - about 6 changes.  I'm about to make a pull request with my fixes for you to double check.

There are 6 or so other warnings that I'll need your help with.  Three from old news items that look like Ensembl-era links:

```
src/docs/news.PomBase/2004-04-30-methods-volume-33-issue-3.md:8:  fission-yeast-papers-methods-volume-33-issue-3
   [Table of Contents](/fission-yeast-papers-methods-volume-33-issue-3) (at

src/docs/news.PomBase/2013-12-08-pombase-data-update-3.md:5:  calendar
   available as a [calendar](/calendar) or a [list](/events). The

src/docs/news.PomBase/2013-07-29-connecting-pombase.md:3:  community/mailing-lists
   To complement the [mailing list](/community/mailing-lists) and twitter
```

This one I wasn't sure what to change the link to:

```
src/docs/documentation/gene-page-gene-ontology.md:77:  browse-curation/fission-yeast-go-slim-terms
   7.  [GO Slim](/browse-curation/fission-yeast-go-slim-terms) terms
```

These two warnings are because it's not possible to link directly to a news item at the moment.  Perhaps we could just remove the 2020-09-11-hermes-transposon-data.md news item?

```
src/docs/news.PomBase/2020-09-11-hermes-transposon-data.md:4:  news/2020-09-11-hermes-transposon-data-long
   [Read more](/news/2020-09-11-hermes-transposon-data-long) about the

src/docs/news.PomBase/2020-09-11-hermes-transposon-data.md:13:  news/2020-09-11-hermes-transposon-data-long
   [summary](/news/2020-09-11-hermes-transposon-data-long) of the work.
```

**Comment by mah11** [comment] 2021-08-18 09:24
Thanks again :)

>      src/docs/news.PomBase/2004-04-30-methods-volume-33-issue-3.md:8:  fission-yeast-papers-methods-volume-33-issue-3
>         [Table of Contents](/fission-yeast-papers-methods-volume-33-issue-3) (at

For this one I removed the PomBase link.

>     src/docs/news.PomBase/2013-12-08-pombase-data-update-3.md:5:  calendar
>        available as a [calendar](/calendar) or a [list](/events). The

I deleted the links and added a note saying "out of date now".

>     src/docs/news.PomBase/2013-07-29-connecting-pombase.md:3:  community/mailing-lists
>        To complement the [mailing list](/community/mailing-lists) and twitter

I slotted in the current mailing list link (we don't maintain a separate page just to link to it any more).

>     src/docs/documentation/gene-page-gene-ontology.md:77:  browse-curation/fission-yeast-go-slim-terms
>        7.  [GO Slim](/browse-curation/fission-yeast-go-slim-terms) terms

Oops, I missed that one back when I updated documentation to account for adding the GO MF & CC slims. I updated it to point to the documentation page, which also matches the occurrence in the same file that I did fix earlier.

> Perhaps we could just remove the 2020-09-11-hermes-transposon-data.md news item?

Sure - it made sense to have short and long versions when it was actually news (the full-length one was awfully long to cram onto the front page), but it's old now. Keep the one with "long" and we won't lose any info. I haven't done this, though, so go ahead whenever.

**Comment by kimrutherford** [comment] 2021-08-19 00:24
Thanks for all the fixes.

> haven't done this, though, so go ahead whenever.

I've done that so now there are no warnings for the PomBase documentation.

**Comment by kimrutherford** [comment] 2021-09-01 04:48
Hi Midori.

Thanks for all the documentation work.  It's looking good!

I noticed some mangled output from the script that processes the markdown.  There were some broken IDs.  It's fixed now.  

I've also fix some URLs.  The documentation was wrong for the `$[base_url}` variable.  It was documented as:
```
${base_url}  |  www.pombase.org  |  www.japonicusdb.org
```
but it's actually:
```
${base_url}  |  https//www.pombase.org  |  https://www.japonicusdb.org
```

So I've fixed a few cases like this:
```
[http://${base_url}/query](/query)
```

**Comment by mah11** [comment] 2021-09-01 08:41
Thanks! I always feel like I'm playing with fire when FAQ IDs are involved.

I think the only big thing outstanding is to slot in "base_url" for oodles of download locations ... which is waiting for directories and files to be organized in JaponicusDB to parallel the PomBase organization. (I'm going on the assumption that that's an OK idea inherently, and less work than editing the documentation to keep up with different locations between the two.)

One small thing:
> https//www.pombase.org 

typo - missing `:`

**Comment by kimrutherford** [comment] 2021-09-01 22:32
> I think the only big thing outstanding is to slot in "base_url" for oodles of download locations ... which is waiting for directories and files to be organized in JaponicusDB to parallel the PomBase organization. (I'm going on the assumption that that's an OK idea inherently, and less work than editing the documentation to keep up with different locations between the two.)

I've made a seaparate issue about that as this one is getting a bit long: #78

> One small thing:
>
> >  https//www.pombase.org
>
> typo - missing :

Fixed!

**Comment by ValWood** [comment] 2021-09-09 11:25
Close and new tickets for new issues?

**Comment by mah11** [comment] 2021-09-09 11:26
> Close ...?

OK with me

**Closed** 2021-09-09 12:55 UTC
Labels: needed for release
